# environment settings
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Xl/1tsTKbC1cm2R3wWiWRWttysirHDLfKVr6XZP/gICYgRuEDsntGiUTIYw5n+HYwfiCcB3zg3llF9JPPPzqIbwgKyijHZ7li9EQvQbOnsXmsVyYkIngkmoEGehiCwSvQPjywzFd0gvC1hFOKpKc0h8YNgFJOmLuw7nYYU50dlESMAc1DxdnJQnPo/e34eiASItqu0JNt/fRIhmAdEj7JZEa2rpYgzzql5HHgzJbpGjhTxacbY69dhJbRvE+dKU3Yoz4C9gsTYzpiraAiozcb3MQe43YLfNHP58w2sfhGp3FuYuFcvyp1+zMyczyz7+atkGMatW9FA8tBfHk5sEdH2KZXeSTzU6x72Kd50tekyiot0P6uiU+rpYRcFJRHllypJ6LfqpTMXuoTdKmeLsD9KXSwDW4VPqZ0sZdbp+FqjxmXTR8mcVl30AzzYvjSnjOj49c1L3xLICQuhwilenkQqpqHu/h7sF0QNn8Cb6xdYkP1ugw7OhQj+uqf60iuvZJsT9GqabgO1HeI1QHTdnPSZT8p3qWkGjNAe6gFhN+65VTyf2p0MhhGDdg3ZzX1NiMd6LuPo4FNskUfZ9RdQLag9MOnMhBCfMM1DY2Xq87MckxCEQLghS3zFMYMGTgARcLN8egdpmVqHGYxw7dko/NlYQaFLK0hb7IX8XTZqg/h9g="
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql

# project language
language: ruby
rvm:
  - 2.3.1

# branches to build (whitelist)
branches:
  only:
    - master
    - coverity_scan
    - testing

# commands to run before the install
before_install:
  # download certificate
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# arguments for the bundlerficate for scan.coverity.com
bundler_args: --without production development

# script
script:
  # create database for test environment
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  # prepare test database
  - bundle exec rake db:test:prepare
  # run rspec and cucumber
  - bundle exec rspec spec/
  - bundle exec cucumber features/

# run before script
before_script:
  # create databases for non-sqlite databases
  - mysql -e 'create database my_app_test'
  - psql -c 'create database my_app_test' -U postgres

# success and failure notifications
notifications:
  email:
    recipients:
      - max.nitze@gmx.de
    on_success: change
    on_failure: always

# addons
addons:
  coverity_scan:
    project:
      name: "maxnitze/football_homepage"
      description: "Build submitted via Travis CI"
    notification_email: max.nitze@gmx.de
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search ./"
    branch_pattern: coverity_scan
