# environment settings
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "pBvNdNs3D5gZ2Vyk6XXyXpis/tT7L0TmA8sq/iAHNu7JbeQHR63b+IS/mYTAw7qdfG7vtalEhxDNaV+602obiWzJ1N1+gf32JufRX/IoOpNDJnv9CtNzKDHP4akDypmIPmRtsPe2ZRruqSrSbZ6B09uOcmCE/phgh0sMhLxOeuqLsVNQ4TMEBFRT6u342cLfyKcvFRNNnC+SrX3s4IZwtQZfhldvtH7S2CXOyG0XWCXKLuPXAluGDnAgnKeDTcIN0AT/VjWuhP+ta2qP9oxvxrxUysvTHtdt60/W1bbNBteQuyJg8wU87Jy+ekII53UDxwiuE7IvFzLilQKHRQ+iaJ98SgsedZLQUKJayRsrnosuSQrzOmMQVmxyJVqCAauHRbs8NTxRPxOJW3JaIG9MNFmmDDcrqN2dWJQwoAtz3r6LnAeisjjazmASKZglJum0Gc30zDup+yMF1Mm1MHC7nmpuAQspgTEKM/iCjBvNF+UL63fuFmmNJASXIZtn6GFQrejFI2P48ULbhVKmhdIGXbdHAMafzVfNGm7hmnpRza19zQ9NajHb2nISetJvqlvQHAt5Bz9GoBfLumPYHxW31bdLqZ/bbjGm8IUhW05N0qa+VBvduZEbRPVZhOhodQMgYLJUduRYlstimPKeFOF5RHf+PB3Xv+wOKBGmC9j0V6Y="
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql

# project language
language: ruby
rvm:
  - 2.3.1

# branches to build (whitelist)
branches:
  only:
    - master
    - coverity_scan
    - testing

# commands to run before the install
before_install:
  # download certificate
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# arguments for the bundlerficate for scan.coverity.com
bundler_args: --without production development

# script
script:
  # create database for test environment
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  # prepare test database
  - bundle exec rake db:test:prepare
  # run rspec and cucumber
  - bundle exec rspec spec/
  - bundle exec cucumber features/

# run before script
before_script:
  # create databases for non-sqlite databases
  - mysql -e 'create database my_app_test'
  - psql -c 'create database my_app_test' -U postgres

# success and failure notifications
notifications:
  email:
    recipients:
      - max.nitze@gmx.de
    on_success: change
    on_failure: always

# addons
addons:
  coverity_scan:
    project:
      name: "maxnitze/football_homepage"
      description: "Build submitted via Travis CI"
    notification_email: max.nitze@gmx.de
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search ./"
    branch_pattern: coverity_scan
